export const HTTP_BACKEND = "http://localhost:8000"
export const WS_URL = "ws://localhost:9000"
export const JWT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtYW5AZ21haWwuY29tIiwiaWQiOiJmYzMzOWI4ZS0yZjhmLTQ3OTItOTlhNy0xNGFjYWRlOThkOWQiLCJpYXQiOjE3NzEyNjAxMDMsImV4cCI6MTc3MjQ2OTcwMywiYXVkIjoiVXNlciIsImlzcyI6IlNoYXJlZENhbnZhcyJ9.xibyNAro7zvfJjNoLmBD4H2ijGQ7drruFM_OPI-X7_s"